CREATE TABLE USERS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(30),
SURNAME VARCHAR (30),
TYPE TINYINT,
EMAIL VARCHAR(40),
PASSWORD VARCHAR(20)
);

CREATE TABLE MONEYBAGS (
ID INT PRIMARY KEY AUTO_INCREMENT,
CASH FLOAT,
TYPE TINYINT,
CODE VARCHAR(30),
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS (
ID INT PRIMARY KEY AUTO_INCREMENT,
CASH FLOAT,
FROM_ID INT,
TO_ID INT,
USER_ID INT,
FOREIGN KEY (FROM_ID) REFERENCES MONEYBAGS(ID) ON DELETE CASCADE,
FOREIGN KEY (TO_ID) REFERENCES MONEYBAGS(ID) ON DELETE CASCADE,
FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

INSERT INTO USERS (NAME, SURNAME, TYPE, EMAIL, PASSWORD)
VALUES ('Alexander', 'Kachsheev', 0, 'alexkachsjeev@gmail.ru', 'alekev5469');

INSERT INTO USERS (NAME, SURNAME, TYPE, EMAIL, PASSWORD)
VALUES ('Pavel', 'Sidorov', 2, 'Pavel@mail.ru', 'pavel');

INSERT INTO MONEYBAGS (CASH, TYPE, CODE, USER_ID)
VALUES (0, 2, '0000 0000 0000 0000', 1);

INSERT INTO MONEYBAGS (CASH, TYPE, CODE, USER_ID)
VALUES (0, 2, '0000 0000 0000 0000', 2);

INSERT INTO MONEYBAGS (CASH, TYPE, CODE, USER_ID)
VALUES (1000, 1, '2202 2022 0000 0000', 1);

INSERT INTO MONEYBAGS (CASH, TYPE, CODE, USER_ID)
VALUES (1100, 1, '2202 2022 0000 0040', 2);

INSERT INTO TRANSACTIONS (CASH, FROM_ID, TO_ID, USER_ID)
VALUES (50, 3, 1, 1);

INSERT INTO TRANSACTIONS (CASH, FROM_ID, TO_ID, USER_ID)
VALUES (400, 4, 2, 2);

/*
DROP TABLE USERS;
DROP TABLE TRANSACTIONS;
DROP TABLE MONEYBAGS;
 */